### PR TITLE
Added Japanese translation

### PR DESCRIPTION
**Pull request by naofum**
Hello!

### CODE REVIEW

**Comment by readbeyond** [comment]
Hi @naofum !

Your pull request looks good, and I am fine merging it --- albeit the project is somewhat dead, as I no longer have time to work on it.

However, I think you should add your name (or a nickname if you prefer) to the list of translators in the `help.html` file:

https://github.com/readbeyond/minstrel/blob/master/cordova/src_minstrel/www/help.html#L153

If you can add it and update your PR, I will merge it, thank you.

Apologies for the delay in this reply.

**Comment by readbeyond** [comment]
Also, I think you should add JA to the enumeration in:

https://github.com/readbeyond/minstrel/blob/master/cordova/src_minstrel/www/js/rb.i18n.js#L33

otherwise the Japanese localization will not be available.

**Comment by naofum** [comment]
Hi @readbeyond !

Thanks for your advice.

**Comment by readbeyond** [comment]
Apologies, I did not realize that you updated the commit. Merging now. Thank you.

**Pull request merged**
